
set(CPACK_GENERATOR "WIX")
set(CPACK_WIX_PRODUCT_GUID "A1B2C3D4-E5F6-7A8B-9C0D-1E2F3A4B5C6D")
set(CPACK_WIX_UPGRADE_GUID "D6E4D0F0-7A3B-4A5C-9D1E-0F2A3B4C5D6E")
set(CPACK_WIX_LICENSE_RTF "${CMAKE_SOURCE_DIR}/LICENSE.rtf")
set(CPACK_WIX_PRODUCT_ICON "${CMAKE_SOURCE_DIR}/app_icon.ico")
set(CPACK_WIX_UI_REF "WixUI_InstallDir")
set(CPACK_WIX_CULTURES "en-US")
set(CPACK_WIX_TEMPLATE "${CMAKE_SOURCE_DIR}/wix_template.xml")

include(CPack)
