name: Package-RPM

on:
  push:
    tags:
      - v*

jobs:
  package-rpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Configure CMake
        run: |
          rm -rf build/
          cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Package RPM
        run: |
          cd build
          cpack -G RPM

      - uses: actions/upload-artifact@v4
        with:
          name: packages-rpm
          path: build/*.rpm
