name: Package

on:
  push:
    tags:
      - v*

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y rpm

      - name: Build and Package
        run: |
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          cd build && cpack -G ${{ matrix.os == 'ubuntu-latest' && 'DEB' || matrix.os == 'macos-latest' && 'DragNDrop' || 'WIX' }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.os }}
          path: build/*.${{ matrix.os == 'ubuntu-latest' && 'deb' || matrix.os == 'macos-latest' && 'dmg' || 'msi' }}
