name: Package-RPM

on:
  push:
    tags:
      - v*

jobs:
  package-rpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install RPM tools
        run: sudo apt-get install -y rpm

      - name: Build and Package
        run: |
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          cd build && cpack -G RPM

      - uses: actions/upload-artifact@v4
        with:
          name: packages-rpm
          path: build/*.rpm
