name: Package

on:
  push:
    tags:
      - v* 

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Configure CMake
        run: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: cd build && ctest -C Release

      - name: Package
        run: cd build && cpack -G ${{ matrix.package-type }}
        env:
          matrix.package-type: ${{ matrix.os == 'ubuntu-latest' && 'DEB' || matrix.os == 'macos-latest' && 'DragNDrop' || 'WIX' }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages-${{ matrix.os }}
          path: build/*.${{ matrix.os == 'ubuntu-latest' && 'deb' || matrix.os == 'macos-latest' && 'dmg' || 'msi' }}
