name: Package

on:
  push:
    tags:
      - v*

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean build directory
        shell: bash
        run: rm -rf build/
        if: matrix.os != 'windows-latest'

      - name: Clean build directory (Windows)
        shell: pwsh
        run: Remove-Item -Recurse -Force build/ -ErrorAction Ignore
        if: matrix.os == 'windows-latest'

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCPACK_DEBIAN_PACKAGE_MAINTAINER="Your Name <email@example.com>"

      - name: Build
        run: cmake --build build

      - name: Package
        shell: bash
        run: |
          cd build
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cpack -G DEB
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            cpack -G DragNDrop
          else
            cpack -G WIX
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.os }}
          path: build/*.${{ matrix.os == 'ubuntu-latest' && 'deb' || 
                              matrix.os == 'macos-latest' && 'dmg' || 
                              'msi' }}
