name: Package

on:
  push:
    tags:
      - v*

env:
  GIT_CLONE_FLAGS: "--depth=1 --no-tags"

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global http.sslVerify false

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Clean workspace
        shell: bash
        run: |
          rm -rf build/ || true
          if [ "${{ runner.os }}" == "Windows" ]; then
            rd /s /q build 2> nul || true
          fi

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Configure CMake
        shell: bash
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release \
            -DCPACK_DEBIAN_PACKAGE_MAINTAINER="Sveta <kostikovassveta@gmail.com>"
          if [ "${{ runner.os }}" == "Windows" ]; then
            cmake --build build --target help
          fi

      - name: Build
        shell: bash
        run: cmake --build build --config Release

      - name: Package
        shell: bash
        run: |
          cd build
          case "${{ runner.os }}" in
            "Linux")
              cpack -G DEB
              ;;
            "macOS")
              cpack -G DragNDrop
              ;;
            "Windows")
              cpack -G WIX
              ;;
          esac

      - uses: actions/upload-artifact@v4
        with:
          name: packages-${{ runner.os }}
          path: build/*.${{ runner.os == 'Linux' && 'deb' || 
                             runner.os == 'macOS' && 'dmg' || 
                             'msi' }}
