name: Package

on:
  push:
    tags:
      - v*

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false  # Отключаем автоматическую отмену других jobs

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Для правильной работы git

      - name: Install dependencies
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y rpm
          fi

      - name: Build
        run: |
          rm -rf build/
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Package
        run: |
          cd build
          cpack -G ${{ matrix.os == 'ubuntu-latest' && 'DEB' || 
                       matrix.os == 'macos-latest' && 'DragNDrop' || 
                       'WIX' }}

      - uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.os }}
          path: build/*.${{ matrix.os == 'ubuntu-latest' && 'deb' || 
                              matrix.os == 'macos-latest' && 'dmg' || 
                              'msi' }}
